env: "local" #local, dev, prod
storage_path: "C:/Program Files/Go/GoProjects/url-shortener/Data/Local/storage.db"
http_server:
  address: "localhost:8085"
  timeout: 4s
  iddle_timeout: 60s
  user: "myuser"
  password: "mypass"